import { Order } from "../interface/order";
import { Vehicle } from "../interface/vehicle";
import { generateOrderId } from "../utils/generate-order-id";
import { Notification } from "../context/NotificationContext";

export const originCoordinates = { latitude: 38.71814, longitude: -9.14552 };

export let notificationsStart: Notification[] = [];

export let vehiclesStart: Vehicle[] = [
  {
    plate: "ABC123",
    maxWeightCapacity: 500,
    availableWeight: 500,
    favourite: false,
  },
  {
    plate: "XYZ789",
    maxWeightCapacity: 300,
    availableWeight: 300,
    favourite: false,
  },
  {
    plate: "DEF456",
    maxWeightCapacity: 400,
    availableWeight: 400,
    favourite: false,
  },
  {
    plate: "LMN890",
    maxWeightCapacity: 600,
    availableWeight: 600,
    favourite: false,
  },
  {
    plate: "GHI321",
    maxWeightCapacity: 350,
    availableWeight: 350,
    favourite: false,
  },
  {
    plate: "JKL654",
    maxWeightCapacity: 700,
    availableWeight: 700,
    favourite: false,
  },
];

export let ordersStart: Order[] = [
  {
    id: generateOrderId(),
    weight: 100,
    destination: {
      city: "Lisbon",
      country: "Portugal",
      coordinates: { latitude: 38.70889, longitude: -9.13888 },
      postalCode: "1000-001",
      address: "Rua Augusta 12, 1000-001 Lisbon",
    },
    date: new Date("2024-11-15"),
    observations: "Fragile",
    vehicle: null,
    completed: true,
  },
  {
    id: generateOrderId(),
    weight: 200,
    destination: {
      city: "Madrid",
      country: "Spain",
      coordinates: { latitude: 40.41678, longitude: -3.70379 },
      postalCode: "28001",
      address: "Calle Gran Vía 25, 28001 Madrid",
    },
    date: new Date("2024-11-15"),
    observations: "Handle with care",
    vehicle: null,
    completed: false,
  },
  {
    id: generateOrderId(),
    weight: 150,
    destination: {
      city: "Porto",
      country: "Portugal",
      coordinates: { latitude: 41.15794, longitude: -8.6291 },
      postalCode: "4000-001",
      address: "Avenida dos Aliados 50, 4000-001 Porto",
    },
    date: new Date("2024-11-15"),
    observations: "Urgent",
    vehicle: null,
    completed: false,
  },
  {
    id: generateOrderId(),
    weight: 120,
    destination: {
      city: "Lisbon",
      country: "Portugal",
      coordinates: { latitude: 38.7247, longitude: -9.15027 },
      postalCode: "1000-001",
      address: "Praça do Comércio 8, 1000-001 Lisbon",
    },
    date: new Date("2024-11-15"),
    observations: "Requires refrigeration",
    vehicle: null,
    completed: false,
  },
  {
    id: generateOrderId(),
    weight: 80,
    destination: {
      city: "Barcelona",
      country: "Spain",
      coordinates: { latitude: 41.38506, longitude: 2.1734 },
      postalCode: "08001",
      address: "Passeig de Gràcia 22, 08001 Barcelona",
    },
    date: new Date("2024-11-15"),
    observations: "Fragile",
    vehicle: null,
    completed: false,
  },
  {
    id: generateOrderId(),
    weight: 300,
    destination: {
      city: "Lisbon",
      country: "Portugal",
      coordinates: { latitude: 38.71689, longitude: -9.13922 },
      postalCode: "1000-001",
      address: "Rua da Prata 56, 1000-001 Lisbon",
    },
    date: new Date("2024-11-15"),
    observations: "Large package",
    vehicle: null,
    completed: false,
  },
  {
    id: generateOrderId(),
    weight: 50,
    destination: {
      city: "Porto",
      country: "Portugal",
      coordinates: { latitude: 41.14961, longitude: -8.61099 },
      postalCode: "4000-001",
      address: "Rua de Santa Catarina 200, 4000-001 Porto",
    },
    date: new Date("2024-11-15"),
    observations: "Urgent",
    vehicle: null,
    completed: false,
  },
  {
    id: generateOrderId(),
    weight: 60,
    destination: {
      city: "Lisbon",
      country: "Portugal",
      coordinates: { latitude: 38.73761, longitude: -9.14532 },
      postalCode: "1000-001",
      address: "Avenida da Liberdade 144, 1000-001 Lisbon",
    },
    date: new Date("2024-11-15"),
    observations: "Requires assembly",
    vehicle: null,
    completed: false,
  },
  {
    id: generateOrderId(),
    weight: 400,
    destination: {
      city: "Madrid",
      country: "Spain",
      coordinates: { latitude: 40.42, longitude: -3.7075 },
      postalCode: "28001",
      address: "Plaza Mayor 3, 28001 Madrid",
    },
    date: new Date("2024-11-14"),
    observations: "Handle with care",
    vehicle: null,
    completed: false,
  },
  {
    id: generateOrderId(),
    weight: 250,
    destination: {
      city: "Barcelona",
      country: "Spain",
      coordinates: { latitude: 41.38792, longitude: 2.16992 },
      postalCode: "08001",
      address: "Carrer de Sants 98, 08001 Barcelona",
    },
    date: new Date("2024-11-14"),
    observations: "Fragile",
    vehicle: null,
    completed: false,
  },
  {
    id: generateOrderId(),
    weight: 90,
    destination: {
      city: "Lisbon",
      country: "Portugal",
      coordinates: { latitude: 38.7182, longitude: -9.14013 },
      postalCode: "1000-001",
      address: "Largo do Carmo 18, 1000-001 Lisbon",
    },
    date: new Date("2024-11-13"),
    observations: "Fragile",
    vehicle: null,
    completed: false,
  },
  {
    id: generateOrderId(),
    weight: 110,
    destination: {
      city: "Madrid",
      country: "Spain",
      coordinates: { latitude: 40.4151, longitude: -3.7038 },
      postalCode: "28001",
      address: "Calle de Alcalá 45, 28001 Madrid",
    },
    date: new Date("2024-11-15"),
    observations: "Urgent",
    vehicle: null,
    completed: false,
  },
  {
    id: generateOrderId(),
    weight: 70,
    destination: {
      city: "Porto",
      country: "Portugal",
      coordinates: { latitude: 41.1459, longitude: -8.6095 },
      postalCode: "4000-001",
      address: "Praça da Ribeira 10, 4000-001 Porto",
    },
    date: new Date("2024-11-15"),
    observations: "Requires refrigeration",
    vehicle: null,
    completed: false,
  },
  {
    id: generateOrderId(),
    weight: 95,
    destination: {
      city: "Lisbon",
      country: "Portugal",
      coordinates: { latitude: 38.72102, longitude: -9.13985 },
      postalCode: "1000-001",
      address: "Rua Garrett 35, 1000-001 Lisbon",
    },
    date: new Date("2024-11-15"),
    observations: "Handle with care",
    vehicle: null,
    completed: false,
  },
  {
    id: generateOrderId(),
    weight: 200,
    destination: {
      city: "Madrid",
      country: "Spain",
      coordinates: { latitude: 40.4167, longitude: -3.703 },
      postalCode: "28001",
      address: "Paseo del Prado 18, 28001 Madrid",
    },
    date: new Date("2024-11-15"),
    observations: "Fragile",
    vehicle: null,
    completed: false,
  },
];
