name: Run Tests
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --production
      - name: Build
        run: CI=false REACT_APP_ENVIRONMENT=$ENVIRONMENT REACT_APP_STRIPE_PK=$STRIPE_PK REACT_APP_DESARQUIVADOS_API_KEY=$DESARQUIVADOS_API_KEY REACT_APP_DESARQUIVADOS_PAYMENTS_KEY=$DESARQUIVADOS_PAYMENTS_KEY REACT_APP_AWS_REGION=$AWS_REGION REACT_APP_AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID REACT_APP_AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY yarn build
      - name: Run Jest tests
        run: yarn test
